### ISSUE TITLE
pfSense/vcenter and other HTTPS apps not loading

### ISSUE THREAD

**Issue by Electronickss** [mescon/Muximux#102]
I have muximux configured to load over https. However I cannot access other https services on my network. Does that still require the ignore x-frames-header workaround?

**Comment by mescon** [comment]
That depends on wether or not the application you are embedding sends the Content-Security-Policy or the X-Frame-Headers header.
If you are trying to embed something that sends the header, then try the workaround with the plugin mentioned in the README or see if you can disable the header being sent from the application you are embedding.

**Comment by Electronickss** [comment]
@mescon thank you. I misunderstood the issue earlier, thinking the x-frame-headers only applied to different encryption levels. 

For anyone running pfsense (since I saw it was requested several times in issues) this link their forums describes how to disable it within the app.

https://forum.pfsense.org/index.php?topic=69108.0. I only needed to do the first 2 out of the 4
