### ISSUE TITLE
"Muxiumux is loading..." STUCK!

### ISSUE THREAD

**Issue by seanvree** [mescon/Muximux#103]
Great work Sir!!!!

Windows 10E
Muximux ver: DEVELOP c6740ad 
IIS 7.0 (Muximux is in the root webserver dir)
PHP 7.1.0 x64 (PHP is working as I can get to localhost/phpinfo.php and get all the server config)
Compiler: MSVC14 (Visual C++ 2015)

So when I access localhost/muximux it loads the default page (Plex.tv) from the config file, but it doesn't load any of the containers, however, there is a small window in the bottom right of the browser that syas "musxiumx is loading." and it just hangs.  Browser is fully functional, it's just like it doesn't load any of the actual Muximux styles. Weird. 

This is the only thing I have in my logs:
I/Thu, 29 Dec 2016 00:39:27 -0800: Refreshing branches from GitHub - automatically triggered.
I/Thu, 29 Dec 2016 00:48:32 -0800: Refreshing branches from GitHub - automatically triggered.

Tried different browsers. 
http and https

I upgraded my webserver and a lot of other components, I also switched to the develop branch, so it could be a number of things.

Again, great work on this!

**Comment by d8ahazard** [comment]
If you could please, get a copy of your settings.ini.php, remove any personal URL's, and paste it somewhere I can take a look at it's contents.  Also, if you could try loading the page again, then look for any relevant errors in your php log.

**Comment by seanvree** [comment]
@d8ahazard , 

I had to rip out PHP and everything associated it to get it to work. Took me a while!!! However, I'm now able to load index.php, however, no icons are showing up.  Here's my console log:


combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:1 Uncaught Error: Syntax error, unrecognized expression: #Sonarr_(TV)-scale option[value="0.7"]
    at Function.fa.error (combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:1)
    at fa.tokenize (combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:1)
    at fa.select (combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:1)
    at Function.fa [as find] (combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:1)
    at n.fn.init.find (combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:1)
    at n.fn.init (combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:1)
    at n (combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:1)
    at HTMLLIElement.<anonymous> (combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:62)
    at Function.each (combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:1)
    at n.fn.init.each (combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:1)
fa.error @ combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:1
fa.tokenize @ combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:1
fa.select @ combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:1
fa @ combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:1
find @ combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:1
n.fn.init @ combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:1
n @ combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:1
(anonymous) @ combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:62
each @ combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:1
each @ combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:1
scaleFrames @ combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:62
(anonymous) @ combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:12
i @ combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:1
fireWith @ combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:1
ready @ combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:1
J @ combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:1
combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:1 GET http://seanvree.com/fonts/fontawesome-webfont.woff2?v=4.5.0 
(anonymous) @ combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:1
K @ combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:1
n.fn.(anonymous function) @ combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:1
muximuxMobileResize @ combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:13
(anonymous) @ combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:4
i @ combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:1
fireWith @ combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:1
ready @ combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:1
J @ combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:1
index.php:1 GET http://seanvree.com/fonts/fontawesome-webfont.woff?v=4.5.0 
index.php:1 GET http://seanvree.com/fonts/fontawesome-webfont.ttf?v=4.5.0 
combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:51 Uncaught TypeError: Cannot read property '0' of null
    at updateBox (combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:51)
    at combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:13
    at dispatch (combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:1)
    at r.handle (combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:1)
updateBox @ combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:51
(anonymous) @ combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:13
dispatch @ combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:1
r.handle @ combineify.php?type=javascript&files=js/jquery-2.2.4.min.js,js/jquery-ui.min.js,js/jquery.form.min.…:1


settings file:

https://1drv.ms/u/s!AiYxIfR_MQKaje1nmebnCJ59YjqZWA

**Comment by seanvree** [comment]
So I figured this out. Was a problem somewhere with PHP/Fast CGI. 

however, no images are loading.  I'll close this and open a new issue. 

Thanks.

**Comment by PhAzE-Variance** [comment]
Im seeing a simialr problem from a fresh install of the linuxserver.io docker for Muximux on Unraid.  The gui doesnt load styles or images amd it has the Muximux is loading text at the bottom, forever.

**Comment by kwetiaw** [comment]
same here on Rockstor NAS. I tried installing from their GUI as well as manually from terminal. I manage to install this few days ago successfully but then I tried installing again today, I am getting an error Muximux is Loading - link here [http://imgur.com/a/JCtYu](url)

**Comment by kwetiaw** [comment]
@PhAzE-Variance just use a different docker image - I used this one cristiangauma/muximux and they work fine.

**Comment by PhAzE-Variance** [comment]
@kwetiaw I'm running it on unraid so my docker choices are limited to that one at the moment.   It seems they have must of it working,  but things like the 'remove' buttons and icon selection don't work from a tablet or phone.  They work from a browser though.

**Comment by mescon** [comment]
Hey guys - this is currently being tested by the linuxserver.io guys over in this issue: https://github.com/mescon/Muximux/issues/123
