### ISSUE TITLE
New DEVELOP Branch Won't load on Windows

### ISSUE THREAD

**Issue by seanvree** [mescon/Muximux#106]
After the latest DEVELOP update Muximux won't load.

Using behind IIS Server on Windows10E
DEVELOP: LATEST
PHP: 7.1

ScreenShot:

http://imgur.com/a/5Ef52

I'm using the new DEFAULT setting.ini.php file.

FYI:  Latest MASTER branch works fine on the same machine, I have both the latest develop and master branch , I rename the base DIR to test to ensure it's not my machine.

**Comment by mescon** [comment]
Hey!
Have a look at the console to see what error is being thrown - press ctrl+shift+i in Chrome I believe.
This is a recurring bug we're trying to fix. Most likely, this has to do with the theme as well as the filename/path of the theme CSS file.

**Comment by seanvree** [comment]
Yeah, I'm trying to figure it out. Hang tight.

**Comment by mescon** [comment]
Did you get this sorted out? Did you find the problem?

**Comment by seanvree** [comment]
@mescon - No, I went back to the master branch.
