### ISSUE TITLE
Sandbox error?

### ISSUE THREAD

**Issue by seanvree** [mescon/Muximux#107]
Tying to use the speedtest mini app for my IIS Server:

https://support.ookla.com/hc/en-us/articles/234575648#upload_test_configuration

Getting this error:

Failed to load 'https://seanvree.com/speedtest/speedtest.swf?v=2.1.8' as a plugin, because the frame into which the plugin is loading is sandboxed.
w @ swfobject.js?v=2.2:4
3seanvree.com/:1 Failed to load 'https://seanvree.com/speedtest/speedtest.swf?v=2.1.8' as a plugin, because the frame into which the plugin is loading is sandboxed.

I can load the site just fine on the same browser if I Bypass Muximux.

**Comment by mescon** [comment]
I'm not sure what particular setting that application wants, but you are free to change the iframe sandboxing options directly in muximux.php (just search for ``sandbox`` and you'll find it).
