### ISSUE TITLE
Can't get uTorrent WebUI to work

### ISSUE THREAD

**Issue by alternativesurfer** [mescon/Muximux#11]
I've added the following into the config.ini however cannot get it to appear.
Any ideas?
```
[utorrent]
enabled = "True"
default = "false"
name = "uTorrent"
url = "http://xxxxxxxxxxx.com:xxxx/gui/"
landingpage = "True"
icon = "fa fa-globe"
```

**Comment by mescon** [comment]
I think the values are case-sensitive.
Please set ``enabled = "true"`` and  ``landingpage = "true"`` (``t`` instead of ``T``).

Does that fix the problem?

**Comment by mescon** [comment]
No response - I assume this fixed the issue and it is therefore closed.
If this did not fix the issue. please re-open this ticket.
