### ISSUE TITLE
Non-Deferred pages?

### ISSUE THREAD

**Issue by kaotix** [mescon/Muximux#111]
Love the simplicity and look of this, been after something almost as simple as this for a while.
I would, however, like to have non-deferred links to my apps. Instead of having to 'Launch Plex' or 'Launch CouchPotato' why not just take me right there?
I don't see that this adds any additional load (and if it does, I'll take the hit)
Could this be added please?

**Comment by mescon** [comment]
It's already in there. Just uncheck "Landing page" on the entry and it will load directly.
Also, click "Default" on the page you want Muximux to load as default.

**Comment by kaotix** [comment]
Thanks for the heads up, didn't think this was clear from the settings page.
