### ISSUE TITLE
Not setting up a config leads to a blank page.

### ISSUE THREAD

**Issue by fodawim** [mescon/Muximux#12]
Seems like it could be useful to catch the errors thrown and display a user friendly page in case of no config.

>
<b>Warning</b>:  parse_ini_file(config.ini.php): failed to open stream: No such file or directory in <b>/Applications/XAMPP/xamppfiles/htdocs/muximux.php</b> on line <b>7</b><br />

**Comment by mescon** [comment]
Will fix in next update.

**Comment by mescon** [comment]
Fixed in https://github.com/mescon/Muximux/commit/7e1ef962566d8c3584bae40f29e0e7d3db3aa446.
