### ISSUE TITLE
Add entry for radarr

### ISSUE THREAD

**Issue by fryfrog** [mescon/Muximux#120]
Radarr is a great, new Sonarr fork for Movies that is shaping up to be quite awesome. Might be worth adding as a default app.

https://radarr.video/

https://github.com/Radarr/Radarr

**Comment by mescon** [comment]
Absolutely, I'm using it myself - however, the default apps are just for show and the user is meant to change them to whatever they want.
Maybe we'll do it in the future - by replacing Glances or something.

I'll mark this as closed though, as it's very low priority.
