### ISSUE TITLE
Password protect Settings modal

### ISSUE THREAD

**Issue by calvinbui** [mescon/Muximux#122]
In my configuration, I have a simple dashboard I have made as the landing page. This is not password protected as there is no risk here. If I only want an overview of what's happening I take a look at the landing page then leave.

All the other services, NZBGet, Couch, Sonarr, etc. are protected by a password prompt through NGINX. 

The authentication option prompts for a password upon browsing to the URL which is not ideal. The only risk is if someone opens the Settings menu and puts their own services in or fakes the URL to capture my username and password unsuspectingly. 

It'll therefore be beneficial to place the Settings modal behind a password prompt or have an option in the settings.ini.php file to disable it completely.

**Comment by mescon** [comment]
Interesting - I see your point.
As this function was mainly developed by @d8ahazard (as most of the 2.0 stuff was), we'll see what he thinks.

**Comment by 2wheelsdown** [comment]
Can I 'vote' for this too?

I like the 'landing' page with all the app shortcuts, and each of the underlying web apps you can jump to are all password protected using their own functionality, so again the only problem for me is if one of my users decides to monkey around with the settings for Muximux.

**Comment by Leafar3456** [comment]
I'm all in for this feature request. But for now you can disable the settings in settings.ini.php under [settings]

**Comment by johnalanyoung** [comment]
This is definitely a feature I would need because without it, a public facing landing page is open to misuse.

Is there any further updates on this one at all?

**Comment by d8ahazard** [comment]
It's on my list.
