### ISSUE TITLE
Cannot open log file (muximux.log)

### ISSUE THREAD

**Issue by wiscokidd** [mescon/Muximux#128]
I'm having some issues getting this up and running. When I try to access the site I get "Cannot open log file (muximux.log)" this back in the browser. I have nginx and php5 running on ubuntu 14.04 (I tested it with a info.php and everything was working.

**Comment by mescon** [comment]
Did you give your webserver ownership of the entire directory?
chown -R www-data:www-data /directory/where/muximux/is/located for instance.
Or whatever user nginx is running as.

**Comment by wiscokidd** [comment]
That fixed it. Thanks!
