### ISSUE TITLE
Errors - PHP Warning: file_get_contents

### ISSUE THREAD

**Issue by 2wheelsdown** [mescon/Muximux#129]
Output from Caddy web server whilst running:

13/Feb/2017:11:45:35 +0000 [ERROR 0 /] PHP Warning:  file_get_contents(): Unable to find the wrapper &quot;https&quot; - did you forget to enable it when you configured PHP? in C:\Muximux2\muximux.php on line 667

PHP Warning:  file_get_contents(https://api.github.com/repos/mescon/Muximux/branches): failed to open stream: No such file or directory in C:\Muximux2\muximux.php on line 667

PHP Warning:  file_get_contents(): Unable to find the wrapper &quot;https&quot; - did you forget to enable it when you configured PHP? in C:\Muximux2\muximux.php on line 667

PHP Warning:  file_get_contents(https://api.github.com/repos/mescon/Muximux/branches): failed to open stream: No such file or directory in C:\Muximux2\muximux.php on line 667

Followed by the repeated output:

13/Feb/2017:11:45:56 +0000 [ERROR 502 /:/websockets/notifications] EOF

**Comment by mescon** [comment]
Try this in your php.ini file:
```
extension=php_openssl.dll
allow_url_include = On
```
Feel free to re-open this issue if this did not solve your issue.
This is not something wrong with Muximux though, this is your installation so Google is your best bet.

**Comment by 2wheelsdown** [comment]
Hey thanks!  Your suggestion appears to have cleared up the 'file_get_contents' function errors.

However, the " [ERROR 502 /:/websockets/notifications] EOF " output still remains...

**Comment by mescon** [comment]
Weird, because Muximux doesn't use websockets at all. I think that's the application you are trying to serve.

**Comment by 2wheelsdown** [comment]
ok, I'll have to have another dig I guess.  It's odd though because I don't remember this output before putting Muximux in front of the other apps.  But I'll test to make sure.  Thanks again for your help.

**Comment by 2wheelsdown** [comment]
I think it's Plex - I've just noticed on the alerts area that it's just repeating "Unable to listen for events on SERVER", and I'm sure this functionality is enabled by websockets.  So that's currently broken, but to be fair I suspect it's to do with my current reverse web proxy config.
