### ISSUE TITLE
Feature Request: Auto Launch

### ISSUE THREAD

**Issue by f3bruary** [mescon/Muximux#13]
I'd like to be able to browse to the Muximux instance and not click each tab individually and then launch them, but instead it should auto launch all instances upon first visit.

Optionally it could be on per app basis, for example:

`[rutorrent]`
`enabled = "true"`
`default = "false"`
`name = "RuTorrent"`
`url = "https://github.com/Novik/ruTorrent"`
`landingpage = "true"`
`icon = "fa fa-globe"`
__`auto-launch = "true"`__

if I have to click each tab and then launch, then I might as well use bookmarks for each app and load them in different tabs which would be quicker

**Comment by mescon** [comment]
Ehm... did you read anything that the documentation says?
Just set landingpage = "false"

Closed.

**Comment by f3bruary** [comment]
Sorry. I thought that was to set the default page. Thanks for the info.

**Comment by mescon** [comment]
No worries mate, to set the default page, you just set ``default = "true"``, though remember that only ONE item must have default = true!
