### ISSUE TITLE
nginx http basic auth popping up twice

### ISSUE THREAD

**Issue by phairplay** [mescon/Muximux#131]
hi,
i was previously using idashboard and moved over to this last night. i have everything running through nginx with basic auth on each subsite.

on idashboard i had my user name and password saved (chrome android moblie) so i could quickly log in. yet now it pops up all filled as normal then another one pops up with everything blank.

how can i stop this from happening, i've tried removing the saved creds and re-adding but it still does it.

cheers

**Comment by mescon** [comment]
Add the username and password to the URL maybe... like... ``https://user:pass@site.com/servicename/``
