### ISSUE TITLE
Fatal error: Call to undefined function session_status() in /usr/local/www/nginx/muximux.php on line 1110

### ISSUE THREAD

**Issue by Wolfeman0101** [mescon/Muximux#133]
Fatal error: Call to undefined function session_status() in /usr/local/www/nginx/muximux.php on line 1110

I was getting an HTTP 500 error so I turned on PHP  display_errors and now I'm getting that error.  I'm on FreeNAS.

**Comment by colmconn** [comment]
You may need to install the session shared extension for php. I got a similar message last weekend (on FreeBSD 10.3) and resolved it by installing php56-session.

**Comment by Wolfeman0101** [comment]
Thanks installing php56-session fixed that error but now I'm getting this weird formatting issue.

http://i.imgur.com/iMXAmT6.png

**Comment by colmconn** [comment]
you are probably missing support for gzencode. Try installing php56-zlib

**Comment by Wolfeman0101** [comment]
I installed php56-zlib and still getting the weird page format.

**Comment by iancorbitt** [comment]
Which OS/browser are you using?

What OS and software are you hosting Muximux on? Looks like some CSS isn't loading...

**Comment by Wolfeman0101** [comment]
Yeah it's something on Chrome that's breaking it.  I'll figure it out thanks!
