### ISSUE TITLE
2.0 gives white screen and 500 error

### ISSUE THREAD

**Issue by shadowswan** [mescon/Muximux#135]
Having a strange issue when updating from 1.0 to 2.0

Running Nginx Letsencrpyt via https://github.com/linuxserver/docker-letsencrypt 

In config I have 

```
	location /admin {
	auth_basic "Restricted";
	auth_basic_user_file /config/nginx/.htpasswd;
	}
```

This allows me to lock down the /admin directory which is where I run Muximux.

into this directory I pasted the contents of the maxims 1 docker and I am fine but when I go to replace it with 2 I just get a white screen in safari and a 500 error in Chrome. 

I have run chmod 777 and 775 on the directory to try and default permissions with no luck and have tried to restart the docker but nothing.

Any ideas?

**Comment by mescon** [comment]
Sorry, don't know anything about docker myself. Maybe some other gentle soul can help out? Otherwise I suggest you hear with the LinuxServer.io people who run the official docker for Muximux.

**Comment by vortexrap** [comment]
@shadowswan Yep having the same issue here. Little different for me: I do not have auth_basic set, but am using the authentication for Muximux. Here is my nginx:
`
server {
	listen 443 ssl default_server;

	root /config/www;
	index index.html index.htm index.php;

	server_name services.hostname.com;

	ssl_certificate /config/keys/letsencrypt/fullchain.pem;
	ssl_certificate_key /config/keys/letsencrypt/privkey.pem;
	ssl_dhparam /config/nginx/dhparams.pem;
	ssl_ciphers 'ciphers';
	ssl_prefer_server_ciphers on;
	
	client_max_body_size 0;

	location / {
		#auth_basic "Restricted";
		#auth_basic_user_file /config/nginx/.htpasswd;
		include /config/nginx/proxy.conf;
		proxy_pass http://192.168.1.50:8080;
		#try_files $uri $uri/ /index.html /index.php?$args =404;
	}
`

In testing, I am able to get to the login page when accessing services.hostname.com. But when I login, it redirects to services.hostname.com/index.php, and I believe that is the issue.

@mescon is there any way to include a base URL setting for reverse proxies? Sonar, PlexPy, Radarr all have this option for ease of use.

**Comment by mow4cash** [comment]
Did anyone resolve this issue? I'm having the same problem.

**Comment by mescon** [comment]
@vortexrap All URL:s in Muximux are relative, so you could append whatever you wanted in the Docker, provided that nginx/apache/whatever serves it up.. Muximux itself doesn't care what directory it is served from.

**Comment by shadowswan** [comment]
somehow this seems to be working now.... not sure what has changed!
