### ISSUE TITLE
New dropdown menu done!

### ISSUE THREAD

**Issue by mescon** [mescon/Muximux#14]
First make sure you get the latest version, either by [downloading the latest ZIP-file](https://github.com/mescon/Muximux/archive/master.zip), or by doing ``git pull`` in your terminal.

Then, add this to your config.ini.php:
```
[general]
title = "Muximux - Application Management Console"
enabledropdown = "true"
```

When you've done that and you decide you want an item to move to the
dropdown menu, just add ``dd = "true"`` to the block. Like this:

```
[nzbget]
enabled = "true"
default = "false"
name = "NZBGet"
url = "https://nzbget.net/"
landingpage = "true"
icon = "fa fa-download"
dd = "true"
```

If want to disable the dropdown entirely, just do ``enabledropdown =
"false"`` under ``[general]``.

Make sure you watch config.ini.php-example for some examples if you're unsure.

**Comment by kylerw** [comment]
Nice work. Any thought into merging the others into the dropdown if the screen size is too small or the browser is down below a certain size?

**Comment by mescon** [comment]
Absolutely - I just haven't had the time just yet.
That functionality would close #3 and this is also what I'm referencing in https://github.com/mescon/Muximux/commit/6a68cc6cc2cd30526647917b90c2e6f3407d14e7.

I'll have a look at it in the weekend, or if you want to go about it yourself?
Let me know!
