### ISSUE TITLE
Frame loading of a text file not working (gives black screen)

### ISSUE THREAD

**Issue by TimoVerbrugghe** [mescon/Muximux#143]
Hi Mescon,

I've started upgrading to Muximux 2 and testing the 12 tabs I've set up (Sonarr/Radarr/Deluge/Nzbget, etc...). Everything is working, except for a simple log file of my backup that I keep in the root directory of my apache server. When I load it through Muximux, I just get a blank screen.

My Apache root directory is /srv/http. The log file is /srv/http/backup.log. Muximux is set to https://www.#######.com/backup.log (actual domain redacted)

I don't see any errors in my apache logs and when I look at the html code generated by muximux, the text file is actually loaded in its frame. But my screen is just black: http://imgur.com/a/U0rwk

Pastebins:
Backup.log: http://pastebin.com/n6tujTQ8
Muximux.log: http://pastebin.com/EusWppA6

Tried going to the url directly -> works
Made sure permissions are correctly set on the file & the muximux folder (both in /srv/http)
Urls to proxied services do work

**Comment by mescon** [comment]
That may be because the default text color is black, and the iframe background color is black.
Try changing the background color of the iframe (in the CSS) to white.

**Comment by TimoVerbrugghe** [comment]
@mescon Yes, changing the background color of the iframe in a separate css theme did the trick ;). Thanks for reply!
