### ISSUE TITLE
Thank you!!!!!

### ISSUE THREAD

**Issue by MrMxyzptlk** [mescon/Muximux#144]
Wow I've been searching for exactly this kind of application for a while now.
This near perfect for my needs, I didn't want to have to reinstall and reconfigure all of my apps, instead your genius has allowed me to point to my current setup!

YESSS!

How do I make a donation?

**Comment by mescon** [comment]
Aww, schucks :-)

No donation is necessary, but if you insist you are free to send Bitcoin to ``18bTaXnra3WfdATrDVmX9QkLy4EUjoZyxx``.
