### ISSUE TITLE
Plex black screen

### ISSUE THREAD

**Issue by MrMxyzptlk** [mescon/Muximux#145]
When I click on the Plex tab, it goes to Plex.tv like it should.
I login and click launch, then the Plex tab window just turns black and nothing....

**Comment by mescon** [comment]
Hey!
Yes, this is because plex.tv sends the ``X-Frame-Options: DENY`` header when you visit it.
You can circumvent it by using this plugin for Chrome/Opera/Chromium: https://chrome.google.com/webstore/detail/ignore-x-frame-headers/gleekbfjekiniecknbkamfmkohkpodhe
