### ISSUE TITLE
Load Iframes through redirects to share ssl

### ISSUE THREAD

**Issue by jknight2014** [mescon/Muximux#148]
So, I was thinking of the SSL issue. The issue as I understand, is the iframes load the services directly. Meaning you need forwarding and everything setup for all your services. 

If you could leverage reverse proxies you could load all your interfaces through example.com/service-name. Where example.com is your muximux. Include the Let's Encrypt libraries and you can have full SSL in minutes for free.

**Comment by mescon** [comment]
You just described exactly what nginx already does. This is way beyond the scope of Muximux itself.
