### ISSUE TITLE
Black Background?

### ISSUE THREAD

**Issue by seanvree** [mescon/Muximux#149]
I assume that this is because of the HTML/CSS code, but some of the pages I add have a black background and I can't see the content.  I can tell the content is there by selecting all...but it's like the Mux code is overwriting the app code?

make sense?

**Comment by mescon** [comment]
The content you are embedding does not declare any background at all, and therefore the CSS from Muximux is the only background declared for the iframe.
Try just setting the CSS to background: #fff; or something.

**Comment by seanvree** [comment]
@mescon  - 

Are you talking setting the MUXIMUX background CSS? or the app?  right now, my settings.ini looks like this:

[general]
title = "Vree"
branch = "master"
theme = "modern"
color = "#ffffff"
updatepopup = "true"
tabcolor = "true"
rssUrl = OMIT
userNameInput = OMIT
password = OMIT

[settings]
branch_changed = ""
sha = "18ecfb7a9205e719a93aa8cfb00530b449021239"
enabled = "true"
default = "false"
name = "Settings"
url = "muximux.php"
landingpage = "false"
icon = "fa-cog"
dd = "true"
branches[develop] = "988867561d1163d69ccf4a615d8129247faeca2c"
branches[master] = "18ecfb7a9205e719a93aa8cfb00530b449021239"
branches[parseError] = "14ea3581389e329e27c496367b2b85b15fc106f9"
branches[saveProblem] = "4d16f3f4b1d7fb18bac5d8ed09b9a45dbe6711ff"
last_check = 1490671570

**Comment by seanvree** [comment]
actually @mescon ,   what does this error mean:

Refused to display 'http://OMIT::3000/' (app URL) in a frame because it set 'X-Frame-Options' to 'sameorigin'.

**Comment by mescon** [comment]
Read my post again please. I say exactly what I mean in that.
The second question which is unrelated to this issue is already documented in the README.

**Comment by seanvree** [comment]
got it. thanks.
