### ISSUE TITLE
Disabled config blocks can appear in the dropdown if "dd" config item is set to true.

### ISSUE THREAD

**Issue by BrowncoatShadow** [mescon/Muximux#15]
## Scenario
Given I have a config block in config.ini.php
And it is configured `enabled = "false"`
And it is configured `dd = "true"`
When I navigate to Muximux's dropdown menu
Then I should not see the disabled item

## Deviation
Disabled blocks still appear in the dropdown menu if `dd = "true"`. However, it does not appear that these items are functional. (Not extensively tested.)

## Proposed Resolution
The `enabled` config item should take highest priority. A cursory glance at muximux.php gives me the impression that this is how it was intended to work, however I do not know php well enough to propose a code fix.

**Comment by mescon** [comment]
Thanks for the bug report - I'll get it fixed probably within 36 hours or so (the work week just started again).
