### ISSUE TITLE
New install - Fatal error: Cannot redeclare class in Muximux 2.0

### ISSUE THREAD

**Issue by wglassbrook** [mescon/Muximux#150]
Muximux 1.0 works flawlessly. New install of 2.0. Permissions set and on opening in browser...

Fatal error: Cannot redeclare class ComposerAutoloaderInitaaa161de2c47514ec2f8a3b9623e8014 in [webroot]/[muximux]/vendor/composer/autoload_real.php on line 6

**Comment by d8ahazard** [comment]
You have conflicting files.  Try deleting the entire muximux directory (except your config) and then downloading 2.0.  Specifically, you need to delete/replace the /vendor folder.
