### ISSUE TITLE
Can't get Spotify web app to work with Muximux

### ISSUE THREAD

**Issue by deadman36g** [mescon/Muximux#152]
I have added Spotify with the url https://open.spotify.com/browse/featured

I receive the error "Oooops, something went wrong with the playback. Reload" but I select reload, and receive the same message

I was thinking it had to do with the https in the url, but I use Pocket, which also has https and it works fine with Muximux

**Comment by mescon** [comment]
Read the readme. It explains what's happening.

**Comment by deadman36g** [comment]
I am sorry, but I have read the readme but still am not sure of the problem.

My Muximux is not using https, and I am using the chrome plugin "Ignore X-Frame headers"
