### ISSUE TITLE
Background of chosen webapplication turns black

### ISSUE THREAD

**Issue by aroundmyroom** [mescon/Muximux#161]
When using Muximux with one of the latest updates of that webapp my layout of one webapplication gets turned totally different with the colours

![image](https://user-images.githubusercontent.com/250108/29267111-97211022-80e7-11e7-8098-1c8af3140e85.png)

when using the webapplication without Muximux all is ok
![image](https://user-images.githubusercontent.com/250108/29267144-c4b48f32-80e7-11e7-8841-e8eccc1cc406.png)

what can be causing this? Can it be a setting? or is it a  bug?

**Comment by mescon** [comment]
That's the default background color inside of the default CSS theme you are using. You could either just look inside the theme CSS you are using and change the iframe background-color to ``#ffffff`` or you could copy your current theme and name it "My superduper theme.css" if you wanted to, and change it in there, and then change to that theme.
