### ISSUE TITLE
Reverse Proxy - Feature Request

### ISSUE THREAD

**Issue by DrEVILish** [mescon/Muximux#163]
MuxiMux in a Docker container is the perfect front end, for linking all my apps together, but I have to expose all the services outward facing.

I'd like to have muximux as my single outside package and use internal routing through muxi to reach my apps. Adds a layer of security and also it's already built into docker using links, i.e link Sickrage-Container1 as sickrage, then to access sickrage you just http://sickrage/ rather than having to port forward or setup individual external services. When you want to add or change a service you just have to docker link it to muximux and external it.

**Comment by mescon** [comment]
This is way beyond the scope of Muximux. What you are describing is exactly what nginx was written for. To act as a reverse proxy.
Muximux is not that big of a project that we should start competing with nginx, apache and other reverse proxies just for the sake of convenience, when outstanding, free and open-source projects already fulfill this purpose and does an excellent job at it.

Closed.
