### ISSUE TITLE
Protect Sonarr + Radarr + Transmission via single login?

### ISSUE THREAD

**Issue by joq3** [mescon/Muximux#172]
Hi,

I tried Muximux for the first time yesterday, like the look and the function. But the main reason for wanting to keep everything in one place is to only need one login for everything.
Is it possible to deactivate login for Sonarr + Radarr + Transmission and protect them with Muximux somehow?
Right now all my services are reachable from SSL domains like sonarr.domain.com etc.

Is this something that is possible?

Thank you!

**Comment by mescon** [comment]
Yes, but not via Muximux. You'd have to use nginx or apache to run a reverse proxy and serve everything via that - and then enable HTTP Basic Auth to password protect it.
