### ISSUE TITLE
Plex URL? Screen goes black

### ISSUE THREAD

**Issue by darkboomba** [mescon/Muximux#176]
Hello,

First of all thank you for providing such a great tool!

I just set it up and totally love it. However I can't get the plex button to work. The URL is set to http://plex.tv/web when I open it I get the main plex page asking me to log in, as soon as I hit launch the screen goes black and nothing happens. How can I fix this?

Thanks for reading!

- DarkBoomba

**Comment by mescon** [comment]
Personally I use https://plex.tv/web/?secure=1
Also, I assume you've read https://github.com/mescon/Muximux#important-note-regarding-https ?

Plex blocks any embedding, so you need the addon for it to work.

**Comment by darkboomba** [comment]
Thank you!
