### ISSUE TITLE
Change Background Color

### ISSUE THREAD

**Issue by brando56894** [mescon/Muximux#180]
What CSS file and value do I have to edit to change the background on the login screen from white to black? It clashes with the theme of everything else I have.

**Comment by mescon** [comment]
That depends on what theme you are using. Check ``css/themes/`` and change ``background-color`` in there. ``#000000`` means black, ``#fff`` or ``#ffffff`` means white.

**Comment by brando56894** [comment]
Which one do I need to edit in Modern.css? There are a bunch. None of them are set to #ffffff yet it still appears white. Even in Incognito mode.
