### ISSUE TITLE
Unable to connect to Sabnzbd

### ISSUE THREAD

**Issue by Morphy99** [mescon/Muximux#202]
Have set this up on a new box and I'm unable to connect to my sab instance. Anyone using this?
Double and triple checked the URL restarted, readded, etc.

http://192.168.0.10:8081/sabnzbd is my URL.

I can't see anything in specific in the logs but this line appears a lot in nginx error.log:

`[error] 332#332: *120 FastCGI sent in stderr: "PHP message: PHP Warning:  Invalid argument supplied for foreach() in /config/www/muximux/muximux.php on line 689PHP message: PHP Warning:  Invalid argument supplied for foreach() in /config/www/muximux/muximux.php on line 689PHP message: PHP Warning:  Invalid argument supplied for foreach() in /config/www/muximux/muximux.php on line 689PHP message: PHP Warning:  Invalid argument supplied for foreach() in /config/www/muximux/muximux.php on line 689PHP message: PHP Warning:  Invalid argument supplied for foreach() in /config/www/muximux/muximux.php on line 689" while reading upstream, client: 192.168.0.95, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.0.10", referrer: "http://192.168.0.10/"`

**Comment by mescon** [comment]
The error logs are unrelated I believe.
If you create a text file with these contents:
``<iframe src="http://192.168.0.10:8081/sabnzbd" width="100%" height="100"></iframe>`` and open it, does sab display as it should?
Otherwise I'm wondering if they are setting a HTTP header that prevents embedding it inside an iframe.

Also, is this on the latest version of master? Or are you using develop branch?

**Comment by mescon** [comment]
Oh, also - check your settings.ini.php file and see if there is anything strange in there... unfortunately there's a bug where it can be overwritten. I think @d8ahazard had a fix for it, but its not merged to master.

**Comment by Morphy99** [comment]
> The error logs are unrelated I believe.
> If you create a text file with these contents:
> `<iframe src="http://192.168.0.10:8081/sabnzbd" width="100%" height="100"></iframe>` and open it, does sab display as it should?
> Otherwise I'm wondering if they are setting a HTTP header that prevents embedding it inside an iframe.
> 
> Also, is this on the latest version of master? Or are you using develop branch?

Nope say's it can't connect. I'm using master from Linuxserver.io docker addon on Libreeelec.

Ahhh, a quick google led me to disable this option in Sab:

Config > Specials > x_frame_options

I did see that but the x threw me off. I should've just tried it shouldn't I! Sorry!
