### ISSUE TITLE
Question: Which URL should I be using?

### ISSUE THREAD

**Issue by BigJazzz** [mescon/Muximux#207]
I'm setting Muximux up to be my external portal to all my apps inside my home network. I'm using a reverse proxy with SSL to assist with this (and internally it works amazingly!). The question I have is: what URL should I be adding for external access? I feel like the answer is really obvious, but I thought I'd ask for clarification. I.e. should I be adding the internal ip:port, or should I be using a FQDN? I suppose if I'm using a reverse proxy that's handling the internal port forwarding I can close up the ports in my router?

Apologies for what I feel is a super-basic question, but I'm struggling to work through it in my head. TIA.

**Comment by mescon** [comment]
You use your external fqdn, telling you browser where to go.

I've only got port 443 (https) open on my router, directing that to a
server in my local network (192.168.x.x). That's where I have the reverse
proxy running (I use nginx). The reverse proxy is answering to
muximux.example.com and my services are muximux.example.com/nzbget/ for
example. So I would configure muximux to use that url for nzbget.

Den tors 17 juni 2021 07:52Jarryd Pearson ***@***.***> skrev:

**Comment by BigJazzz** [comment]
Thanks so much. I really appreciate the info!
