### ISSUE TITLE
Plex in Muximux not working

### ISSUE THREAD

**Issue by dobage** [mescon/Muximux#209]
I found another post about using the URL from the XML > Connection protocol="https" address=x.x.x.x port=xxxxxx the uri=etc

I have tried both the internal and external an I can not get either to work.  I am only using inside my network.  So local so be fine.

I am running Muximux out of a docker and Plex is on a Windows machine.

I checked an I am on the current linuxserver.io docker build (latest)

**Comment by mescon** [comment]
The only way to embed Plex is to remove the headers that Plex sets, that prohibits embedding it.
Put Plex behind a reverse proxy that strips the headers, and it'll work.

There's plenty of guides and examples on how to do that around the web, if you just google it.
