### ISSUE TITLE
Change "Save application" to just save on "lose focus"

### ISSUE THREAD

**Issue by mescon** [mescon/Muximux#22]

**Comment by SyNiK4L** [comment]
Double check it to see if u see any weirdness when u get a chance. It looks good from my end though.

**Comment by mescon** [comment]
Seems to work nicely, though it seems names can't contain spaces... Try doing "Plex Requests" and it will be renamed to "Plex_Requests".

**Comment by SyNiK4L** [comment]
Whoops thats a typo. The section should be the only thing with the underscores in it.

**Comment by SyNiK4L** [comment]
Fixed
