### ISSUE TITLE
Cant access external site?

### ISSUE THREAD

**Issue by mtehonica** [mescon/Muximux#26]
Not sure if I'm doing something wrong or if this isn't supported but I can't get an external site to to load in a tab.  For example, I have an external server (whatbox.ca) that I'd like to display in a tab.  I get get a white page.  I tried changing it to just google to see if that would work but it looks like anything outside of the local network doesn't work.  Is this supported and I just have a problem with my install/server? Or is this just not supported?

**Comment by mescon** [comment]
Absolutely you can - this is the whole reason for Muximux :-)

Are you serving Muximux from HTTP or HTTPS?

Can you try a site such as https://couchpota.to instead and see if that works?
If it doesn't I'm not quite sure what issue you've got going on.
If it works, it might be that whatbox.ca and/or Google simply refuses to be framed inside an iframe (like we're doing here). They might be sending a ``X-Frame-Options: Deny`` header.

If that's the case, try installing the plugin here: https://chrome.google.com/webstore/detail/ignore-x-frame-headers/gleekbfjekiniecknbkamfmkohkpodhe

**Comment by mtehonica** [comment]
Yup, that was it!  Added the ignore x-frame headers plugin to Chrome and it immediately worked!

Thanks!
