### ISSUE TITLE
On update screen, date math is wrong.

### ISSUE THREAD

**Issue by fodawim** [mescon/Muximux#31]
Currently it states that the last update on github was 70 days ago, when in reality it should be 1 day.

**Comment by SyNiK4L** [comment]
After I just pushed up this commit it seemed to have fixed this. Although, lets check it again tomorrow and see what it says. There was definitely some weird math going on. Although, this has been working perfectly. Thanks for submitting a bug report. Its much appreciated

**Comment by mescon** [comment]
Closed by https://github.com/fodawim/Muximux/commit/cad529d0b18f82512b145baa9e4cb5f3489d2f60
