### ISSUE TITLE
Bug when hiding drop down

### ISSUE THREAD

**Issue by warplayer** [mescon/Muximux#35]
I unchecked the box for "Enable Dropdown?" and after I saved and reloaded, the site was gone. 500 Server Error.

I went back into settings.ini.php and after a moment of confusion, I realized that instead of changing enabledropdown = "false" to "true", it deleted the whole line! I had to add the line back and set it to false manually to get the site back up.

**Comment by mescon** [comment]
Thanks for the bug report - we'll get it fixed.
