### ISSUE TITLE
Having a dash ("-") in the name of the tab removes the tab entirely

### ISSUE THREAD

**Issue by TheDogg** [mescon/Muximux#36]
I have 2 instances of plexpy running.  So I use 2 tabs for plexpy.  I name them:
- PlexPy - Server 1
- PlexPy - Server 2

if I don't put the dash in the name it works fine, but as soon as the dash is added to the name that tab disappears and the entry in the settings is just blank.

**Comment by SyNiK4L** [comment]
We will have to re-write some of this to handle dashes. As we use dashes to name each input. So adding a dash will break everything. I'll update this once I get this fixed

**Comment by squarefrog** [comment]
As a workaround simply use an em dash – (alt+- on OS X, probably the same on windows).

**Comment by d8ahazard** [comment]
Fixed!
