### ISSUE TITLE
settings button disappears after disabling dropdown menu 

### ISSUE THREAD

**Issue by judhat2** [mescon/Muximux#37]
I just updated to the most current version as of this post, and the settings button disappears after disabling dropdown menu.  I looked at the settings.ini.php and under `[settings]`changed `dd = "true"` to `dd = "false"`. Then the settings button appeared again, but it didn't show me the settings after I clicked it. It was just a white page. Is it possible to make it just an icon on the right side, like the refresh icon?

**Comment by SyNiK4L** [comment]
This has been fixed. Re-pull the latest zip from master

**Comment by SyNiK4L** [comment]
Currently there is no way to make it just a button. We will probably change that in a future release, but for now to fix your problem. Change dd="true" and above that in general set enabledropdown = "true"

**Comment by judhat2** [comment]
Ok, I'll do that.  Thanks for the reply

**Comment by d8ahazard** [comment]
Fixed.
