### ISSUE TITLE
[Feature Request] Ability to bookmark specific services

### ISSUE THREAD

**Issue by some-guy-23** [mescon/Muximux#40]
When you navigate to a specific service, it could add a hash (e.g. #couchpotato) to the URL. Then, on reload of the site would go to that specific service and load it in the iframe.

This way you could bookmark/save the URL for a specific service, within the site.

**Comment by SyNiK4L** [comment]
I like this idea. Although, then what would we do with the landing page option? Ignore it completely if there is a hashtag and use it if there is not one?

**Comment by some-guy-23** [comment]
Hm, hard to say, maybe have that as a global option? Not sure of a clear way to phrase it would be though... "SkipLandingPageOnHashTag"...?

**Comment by mescon** [comment]
Agreed, this functionality would be nice.
We'll sketch something up, or we'd be happy to receive a pull request!

**Comment by mescon** [comment]
This has been published to develop branch.

No functionality to skip landing pages - personally, I think you should just disable the landingpage in case it's a page you're likely to bookmark directly.
