### ISSUE TITLE
Error during 'git pull'

### ISSUE THREAD

**Issue by mannibis** [mescon/Muximux#42]
Tried to pull the latest updates and got this:

```
Updating d46a341..4d16f3f
error: Your local changes to the following files would be overwritten by merge:
	js/functions.js
	muximux.php
Please, commit your changes or stash them before you can merge.
Aborting
```

I swear I did not touch the .php or .js files

Strangely enough, the Show Updates drop-down says:
`Your install is currently up to date!`

**Comment by MaxFlower** [comment]
Try git pull -f if You sure that changes are not critical for your version.

**Comment by SyNiK4L** [comment]
Thats odd, but that normally means you changed the files somehow or they got corrupted on download or install. Thus the files are different from whats on the repo. We're working on the git thing. It still seems to have some bugs. Like Max said you can do -f and it should overwrite the things it thinks is different

**Comment by mannibis** [comment]
Seems like the -f flag doesn't help:

`# git pull -f
Updating d46a341..4d16f3f
error: Your local changes to the following files would be overwritten by merge:
	js/functions.js
	muximux.php
Please, commit your changes or stash them before you can merge.
Aborting
`

I had to do a `git reset muximux.php` and then a `git checkout muximux.php` (same with js/functions.js), then finally a `git pull` and all is good. Weird...

**Comment by SyNiK4L** [comment]
Ah yeah i forgot the -f still would not force it. Good idea on the resets

**Comment by MaxFlower** [comment]
Good idea with git reset. @SyNiK4L  I forgot too)
