### ISSUE TITLE
[Feature Request] Ability to add active tab name as variable in Title

### ISSUE THREAD

**Issue by evanmj** [mescon/Muximux#43]
I keep getting lost when I'm using my dashboard with a few tabs open in chrome...

I like the custom title, but it would be great if you could make it say:

ServerName - $TabName

And have it dynamically replace the window title's $TabName variable with the name of the active tab.

A checkbox might be easier with "append active tab name to title".

Thanks!

**Comment by squarefrog** [comment]
It'd be worth considering prepending the tab name rather than appending, as the end of the title string gets truncated as you open more tabs.

**Comment by evanmj** [comment]
Prepend might be better for that reason, but if implemented as a variable the user could put it anywhere.  I just found myself getting lost in all the tabs, it is  hard for me to get used to working in the muximux "subtabs" when configuring the services.

**Comment by evanmj** [comment]
Thanks, works great!!!

**Comment by mescon** [comment]
Good to hear!
