### ISSUE TITLE
Unable to Access Internal-IP-Tabs Externally

### ISSUE THREAD

**Issue by Frost158** [mescon/Muximux#46]

**Comment by RePeet13** [comment]
Curious as to why this was closed. I have been using muximux to provide an easy portal to my internal services, like plex or deluge, things that I wouldn't want to expose externally (I could go through plex.tv, sure, but it's easier to go direct to server). Is there a way to do this with muximux, or is it actively discouraged?

**Comment by mescon** [comment]
Muximux is not a reverse proxy. To accomplish the task of accessing internal applications from an external client, you'd need to setup a reverse proxy.

Read up on nginx (a reverse proxy software) or Apache which can act as a reverse proxy with the help of mod_proxy.

http://www.htpcbeginner.com/couchpotato-apache-reverse-proxy/

**Comment by RePeet13** [comment]
Aha! The solution is to read up on stuff I hadn't encountered yet, sounds good. Thanks for the point in the right direction

**Comment by mescon** [comment]
No problem - good luck!
