### ISSUE TITLE
[Feature request] Change tab color on mouse rollover 

### ISSUE THREAD

**Issue by judhat2** [mescon/Muximux#48]
To begin with, I'm loving the changes that have been made from the original project.  Next, is it possible to change the tabs to a different color on a mouse rollover like it already does with the refresh button and dropdown menu?  I would really appreciate it if this was implemented.

**Comment by mescon** [comment]
This is already the default behavior.
You are free to change the ``:hover`` color to anything you desire inside of style.css.

**Comment by judhat2** [comment]
Thanks for the reply.  For some reason, only the refresh and drop down menu change colors on a mouse hover in my broswer.  I looked in the style.css, and there are many lines with `:hovor`.  Can you tell me which specific one controls the tab hover color? Thanks

**Comment by mescon** [comment]
Sorry, try some different ones - try just setting hover color to #ff0000 and it will be red, and then you can easily see which one that controls it.

**Comment by judhat2** [comment]
For what it's worth, I finally got the tabs to change colors on a mouse over.  I removed `.no-touch` from this part of the code on line number 115.  I hope I didn't break anything else though...
```css
.no-touch .cd-tabs-navigation a:hover, #reload:hover {
    color: #f1f3f2; /* Hover text colour */
    background-color: rgba(233, 230, 202, 0.3);
```
