### ISSUE TITLE
Scrollbar always visible

### ISSUE THREAD

**Issue by MartinAyla** [mescon/Muximux#49]
Hi

Thanks a lot for Muximux, it's great :)

When I have only one row of items, the scrollbar is always visible (see screenshot), can this be fixed?

If I have two rows it's not visible.

![screen shot 2016-02-09 at 12 27 42](https://cloud.githubusercontent.com/assets/3063746/12915074/c24aabe0-cf28-11e5-80b5-2e54fbd1cb4d.jpg)

**Comment by MartinAyla** [comment]
I'm using latest master on Safari (OS X 10.11.3).

**Comment by Tenzinn3** [comment]
Same issue, only happens at 1080p on my monitor though, weird.

**Comment by mescon** [comment]
Hm, I haven't tried this on Safari. I'll see if I can get my old Mac install to work.
Looks fine in Chrome, Internet Explorer, Edge, Opera and other webbrowsers I assume - or can you replicate the same effect on Chrome/Opera?

**Comment by MartinAyla** [comment]
@mescon It looks fine in Chrome, so it looks like it only needs to be fixed for Safari.

**Comment by alienx2** [comment]
me too have problem with scrollbar.. solution: add "overflow-y: hidden;" to css

**Comment by mescon** [comment]
@alienx2 Inside what tag did you add it? I don't have a Safari-browser to test it with, so I wouldn't be able to verify if my own fix would work or not.

**Comment by alienx2** [comment]
@mescon, add to <nav> like this: <nav style="overflow-y: hidden;"> in muximux.php
