### ISSUE TITLE
Glyphicon Did Not Show

### ISSUE THREAD

**Issue by dcplaya** [mescon/Muximux#5]
I tried adding 

icon = "glyphicon glyphicon-open-folder"

But the icon did not show up. Not sure what is causing it. 
 
Also, if there is a typo in the icon line, it hides the entire entry (ie makes the enable = "false"). I feel like it should display a default error type of icon.

**Comment by mescon** [comment]
You're right - if the icon class is incorrect it should display some default icon. I'll look into it in the weekend.

**Comment by dcplaya** [comment]
I found a fa icon that is basically the same. "fa fa-open-folder" worked fine for me. Just FYI

**Comment by mescon** [comment]
OK cool - I'll close this in the meantime.
