### ISSUE TITLE
Nav Bar Doesn't Extend Fully on iPad

### ISSUE THREAD

**Issue by Kolmain** [mescon/Muximux#51]
I'm using this as a central dashboard for my home on a landcsape Ipad, but the navbar doesn't extend to the full resolution of my iPad 2 when I iframe a PRTG Network Map that is the resolution of the iPad.

**Comment by mescon** [comment]
Please attach a screenshot if you can. In our testing we haven't seen the same behavior.

**Comment by mescon** [comment]
No response on this for 5 days - closing.

**Comment by Kolmain** [comment]
Sorry I didn't see your response, I'll post it later today!

**Comment by Kolmain** [comment]
Here it is @mescon 

Sorry, couldnt easily pull off a screenshot because its in kiosk mode so its a photo.

![img_20160222_231341](https://cloud.githubusercontent.com/assets/8104253/13252191/494a03ea-da03-11e5-9825-4b1e8c296f25.jpg)

**Comment by mescon** [comment]
I've tried hard to replicate this behaviour, but I don't think it has with Muximux itself to do.

Here's a screenshot when emulating landscape in the iPad (all iPads have the same landscape resolution according to http://viewportsizes.com/?filter=ipad)
![image](https://cloud.githubusercontent.com/assets/5875228/13289431/504c0cc0-db10-11e5-8ba4-3a11f7cba2a6.png)

Are you really running the latest version of Muximux?

**Comment by Kolmain** [comment]
Yep, the very latest!
