### ISSUE TITLE
Fresh install giving undefined variable errors

### ISSUE THREAD

**Issue by creoden** [mescon/Muximux#55]
Getting the following two notices on the top of the webpage in Chrome/Internet Explorer when opening a fresh pull of the dashboard

Notice: Undefined variable: dropdownmenu in muximux.php on line 188
Notice: Undefined variable: standardmenu in muximux.php on line 178

**Comment by mescon** [comment]
Sorry 'bout that - will fix.

**Comment by mescon** [comment]
Could you get online on gitter?
https://gitter.im/mescon/Muximux
