### ISSUE TITLE
Plex App won't go fullscreen

### ISSUE THREAD

**Issue by electedgiraffe** [mescon/Muximux#6]
When I'm in the Plex app and I play a video it won't go fullscreen. Is there any fix for that?

The link I'm using for Plex is:
https://app.plex.tv/web/app

It's not a huge deal for me, since I probably won't be playing a video from within Muximux often. It would just be nice if I could.

Thanks for your work! I'm loving Muximux!

**Comment by kylerw** [comment]
Hey @electedgiraffe - I just submitted a pull request for a fix. Waiting on review from @mescon and you should be all set.

**Comment by mescon** [comment]
Merged - good job!
