### ISSUE TITLE
[Add-on] Plex Authentication

### ISSUE THREAD

**Issue by karbowiak** [mescon/Muximux#61]
Hi, would it be possible to implement authentication into Muximux using Plex's oauth(?) stuff ?

Most people use it with Plex anyway, and having it tied to your plex account (while allowing the users the plex server is shared with, access aswell, if allowed) would be pretty awesome :)

**Comment by JigSawFr** [comment]
+1, nice idea.

**Comment by metroplexing** [comment]
Would make sense to have it at a level higher like Nginx using auth_requests to protect your locations (using Muximux for the main location) with your plex credentials (initial access etc.), here's one new project that's capable: [https://github.com/hjone72/PlexAuth](url)

**Comment by d8ahazard** [comment]
Muximux now has native authentication built-in, which, IMHO, negates the need for Plex-based Oauth.  And to be fair - while this can be used with Plex, there is really any number of possibilities that Muximux can be used for.  With that in mind, I think that locking the auth mechanism to any one particular app or service - however prolific and refined, detracts from the overall concept of Muximux.  

Marking this as closed.
