### ISSUE TITLE
Text in couchpotato popups isn't visible

### ISSUE THREAD

**Issue by ismay** [mescon/Muximux#63]
When accessing couchpotato through muximux, the text in the popups (the red squares in the right-bottom corner) isn't visible. When accessing couchpotato directly (same url that's fed to muximux), the text is visible.

Is this a bug, or am I doing something wrong?

**Comment by Goot449** [comment]
I have noticed the same issue, but only on mobile.

**Comment by mescon** [comment]
I'll try to reproduce this behaviour and see if there is anything we can do to fix it.

**Comment by Goot449** [comment]
It seems to be related to couch potato using the screen height however muximux has a bar at the top meaning a popup is pushed down off the screen. If you have trouble replicating on a desktop/phone I can get some screenshots with chrome development tools in my phone when I get a chance.

**Comment by mescon** [comment]
That would be much appreciated - you think you could show me? Just so that I know I'm looking in the right place. AFAIK, Chrome should respect the viewport of the iframe, which is viewport minus the height of the menu.

**Comment by mescon** [comment]
Hey - haven't heard back from you on this. I haven't been able to reproduce the error, so I'm not really sure what I'm looking for. I'll close this for now, but it can be reopened if need be.

**Comment by Goot449** [comment]
Sorry for not responding, I was unable to reproduce the issue after this was reported. Leave it closed unless it arises elsewhere.
