### ISSUE TITLE
[Request] Switch to desktop version for tablets.

### ISSUE THREAD

**Issue by DracoMilesX** [mescon/Muximux#68]
I have a (small) request is it possible to add a button to switch to desktop version? I have a Samsung Galaxy Tab S 10.5 and because it's recognized as a mobile device it automatic puts all the links into the drop down. Which is kinda annoying for a tablet that by default is landscape mode.

**Comment by mescon** [comment]
Sounds interesting - I'll have a look at it.

**Comment by d8ahazard** [comment]
Got the groundwork laid for this, namely, a graceful switch between the two states.  I should have this done tomorrow.  :D

**Comment by d8ahazard** [comment]
This has been added with my latest commit to developer branch.

![override1](https://cloud.githubusercontent.com/assets/1633844/20642194/02c72920-b3ce-11e6-9f61-374ff9566ef3.png)
![override2](https://cloud.githubusercontent.com/assets/1633844/20642193/02c6e9ba-b3ce-11e6-9cfb-37287652c655.png)
![override3](https://cloud.githubusercontent.com/assets/1633844/20642195/02c909fc-b3ce-11e6-950e-64f90f7b1a28.png)
![override4](https://cloud.githubusercontent.com/assets/1633844/20642192/02c5e29a-b3ce-11e6-8551-ddaec57d2976.png)

**Comment by d8ahazard** [comment]
Feature added.

**Comment by DracoMilesX** [comment]
Thanks. Tried it quickly but it didn't show up for me even when I was on develop branch but it went by default to desktop view on my tablet and phone now.

Will try to look what happens on a fresh install later today/tomorrow.
