### ISSUE TITLE
JDownloader web remote doesn't work.

### ISSUE THREAD

**Issue by akanealw** [mescon/Muximux#69]
With JDownloader 2, they moved from direct web interface to an centralized web remote with a linked account to the JDownloader application. When I embed the login page https://my.jdownloader.org/ in Muximux, I can log in and see my account info, but I can't click through to my connected pc. If I right-click on my connected pc, I get context menu options for an image instead of link options, so it's not loading the click through to my connected pc.

Thanks!

**Comment by mescon** [comment]
I'd suggest you try the plugin mentioned here: https://github.com/mescon/Muximux#important-note-regarding-https

**Comment by akanealw** [comment]
I'm sorry, it didn't work. Another option would be to be able to open it in a new tab, but if you don't want to implement that because it defeats the purpose, that's fine.

You may close this at any time.
