### ISSUE TITLE
menu non-responsive to anything

### ISSUE THREAD

**Issue by DropbearNinja** [mescon/Muximux#74]
Hi, don't know if bug or just incorrectly setup by me. Fresh install, on raspbian, using lighttpd and php installed. Web page loads fine using ip/muximux/, and in the main frame the sonarr website loads, but the muximux menu itself is completely non-responsive to input. The settings menu opens on mouseover, but is also non-responsive (and also mostly off screen).

parse_ini_file isn't listed at all in php.ini (so i assume enabled)

the folder ownership is www-data, correct. 

and i installed using git clone

any help please?

**Comment by mescon** [comment]
Check your webbrowser to see if it's blocking anything - this sounds like your webbrowser is not allowing jQuery or something.

**Comment by DropbearNinja** [comment]
I thought so too, but the same thing happens on chrome, firefox, edge, internet explorer, and android...

**Comment by mescon** [comment]
This sounds really weird - first time I've heard of this. Check the webserver logs to make sure that all files are readable (folder may be owned by www-data but are the subfolders and actual files owned by it?).

**Comment by DropbearNinja** [comment]
Found the problem, i'm running pi-hole as well, and the lighttpd config file has this little gem:

i initially ruled pi-hole out as the problem since i disabled the service, didn't realise they had stuff in the webserver config

`
# If the URL starts with /admin, it is the Web interface
$HTTP["url"] =~ "^/admin/" {
        # Create a response header for debugging using curl -I
    setenv.add-response-header = (
        "X-Pi-hole" => "The Pi-hole Web interface is working!",
        "X-Frame-Options" => "DENY"
    )
}

# If the URL does not start with /admin, then it is a query for an ad domain
$HTTP["url"] =~ "^(?!/admin)/.*" {
    # Create a response header for debugging using curl -I
#    setenv.add-response-header = ( "X-Pi-hole" => "A black hole for Internet advertisements." )
    # rewrite only js requests
#    url.rewrite = ("(.*).js" => "pihole/index.js")
}
`

thanks anyway!

**Comment by jstone87** [comment]
I know this was closed but I ran into the same issue with piHole and found a simple workaround, not sure how legitimate it is but I just git cloned it into /var/www/html/admin/muximux and it appears to be working. I don't know how secure or stable it will be but hey.
