### ISSUE TITLE
Kickass and PirateBay un-usable in Muximux

### ISSUE THREAD

**Issue by Flippage** [mescon/Muximux#8]
I'd like to use muximux to get to KAT / TPB, but when I add them I get some strange issues.

TPB takes over the whole page, and navigates away from muximux.

And KAT has an issue with the background color when viewed in muximux.

Any chance you could take a look at those for me ?

**Comment by mescon** [comment]
TPB might be employing some clever code to break out of the frame.
I don't know what KAT is.

Can you give me the config blocks you are using for TPB and KAT?

**Comment by Flippage** [comment]
[kickasstorrents]
enabled = "true"
default = "false"
name = "KickassTorrents"
url = "https://kat.cr/"
landingpage = "true"
icon = "fa fa-cloud-download"

[piratebay]
enabled = "true"
default = "false"
name = "ThePirateBay"
url = "https://thepiratebay.se/"
landingpage = "true"
icon = "fa fa-cloud-download"

**Comment by mescon** [comment]
kat.cr seems to be working fine (at least in the latest version of Muximux - try updating it with git pull or re-download the zip).

TPB is doing ``if (top != self) top.location.href = location.href;`` which breaks out of our iframe.
The only solution I've found so far is a non-standard setting called ``security=restricted`` added to our iframe, which only Internet Explorer has implemented.

**Comment by mescon** [comment]
The security=restricted method also blocks the page from rendering properly, so we can't go that route either.
Haven't found a way to do this, and I'm not sure one exists either, closed unless someone else can pitch in.
