### ISSUE TITLE
Crashes on Chrome for iOS

### ISSUE THREAD

**Issue by Stesus** [mescon/Muximux#82]
My tab crashes often when browsing on my iPhone using Chrome (Specifically when browsing FreeNAS). For some reason, when I "Request desktop version", the crashes stop. It might be a good idea to add the option "Disable mobile version" in the settings. 

![20160906_023315000_ios](https://cloud.githubusercontent.com/assets/12788123/18260181/2d67245a-73a0-11e6-85b0-3fffbf2a0af4.png)

**Comment by mescon** [comment]
Sounds to me that there's a problem with the FreeNAS interface, otherwise the same thing would happen on all tabs.
