### ISSUE TITLE
Move Muximux Folder

### ISSUE THREAD

**Issue by weirdcrap** [mescon/Muximux#84]
This is not so much a Muximux issue (I don't think) and more of a I am new to using git in general and made a mistake and don't know how to fix it.
When I went to clone the repository I made a folder called muximux thinking it would just clone the files into it. Well instead it just made a "Muximux" folder inside my muximux folder. So I deleted both folders and re-cloned the repository but now muximux doesn't work at all and I get these errors in the logs:

`[Thu Oct 13 14:09:55.257815 2016] [:error] [pid 30032] [client xxx.xxx.xxx.xxx:51436] FastCGI: server "/var/www/clients/client1/web1/cgi-bin/php5-fcgi-*-443-xxxxxxxxxxx.xxx" stderr: PHP message: PHP Warning:  require_once(/var/www/clients/client1/web1/web/muximux/Muximux/vendor/composer/autoload_real.php): failed to open stream: No such file or directory in /var/www/clients/client1/web1/web/Muximux/vendor/autoload.php on line 5`

So it is still looking for the old folder path but I am not sure how to fix it?

**Comment by evanmj** [comment]
This would likely be a problem with your webserver's configuration.  What are you using?

**Comment by weirdcrap** [comment]
I am using Apache.

**Comment by evanmj** [comment]
When you did the install, did you checkout maximux in /var/www?  Or did you put it in that long file path?  I've never seen anything like that in apache, so something is doing work behind the scenes to setup multiple clients / sites.

The apache config files typically live in /etc/apache2/conf-enabled

Maybe someone more familiar will chime in and help.

**Comment by weirdcrap** [comment]
There is no muximux in the /var/www folder. I use ISPConfig as a frontend for setting up multiple clients & sites. It creates virtual jailed users and I ran the git clone as one of the jailed shell users so it shouldn't have had permission to write to any folder outside of /var/www/clients/client1/web1

**Comment by evanmj** [comment]
Ah.  Then check to see what is messed up about your file paths for this file:
/var/www/clients/client1/web1/web/muximux/Muximux/vendor/composer/autoload_real.php
Does it exist?

/var/www/clients/client1/web1/web/Muximux/vendor/autoload.php on line 5
^ This is the file that is "running", likely it was initialized with the original data, so the path is incorrect to the 'actual' file.

Either hop in that file and remove the extraneous /maximux/ (and any others that are incorrect), or just fire up a fresh instance on your ISPConfig system and ditch that one that is all messed up.

**Comment by weirdcrap** [comment]
Both files exist.
autoload_real.php is here: /var/www/clients/client1/web1/web/muximux/Muximux/vendor/composer/autoload_real.php
Contents:
`<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitaaa161de2c47514ec2f8a3b9623e8014
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        spl_autoload_register(array('ComposerAutoloaderInitaaa161de2c47514ec2f8a3b9623e8014', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader();
        spl_autoload_unregister(array('ComposerAutoloaderInitaaa161de2c47514ec2f8a3b9623e8014', 'loadClassLoader'));

        $includePaths = require __DIR__ . '/include_paths.php';
        array_push($includePaths, get_include_path());
        set_include_path(join(PATH_SEPARATOR, $includePaths));

        $map = require __DIR__ . '/autoload_namespaces.php';
        foreach ($map as $namespace => $path) {
            $loader->set($namespace, $path);
        }

        $map = require __DIR__ . '/autoload_psr4.php';
        foreach ($map as $namespace => $path) {
            $loader->setPsr4($namespace, $path);
        }

        $classMap = require __DIR__ . '/autoload_classmap.php';
        if ($classMap) {
            $loader->addClassMap($classMap);
        }

        $loader->register(true);

        return $loader;
    }
}
`

autoload.php is here: /var/www/clients/client1/web1/web/muximux/Muximux/vendor/autoload.php
Contents: 
`<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/composer' . '/autoload_real.php';

return ComposerAutoloaderInitaaa161de2c47514ec2f8a3b9623e8014::getLoader();`


All these references to composer makes me think that composer has a file somewhere that is referencing the old incorrect path. I know a little bit about composer from installing drush but nothing that would help me hunt down where this troublesome file is.

**Comment by weirdcrap** [comment]
Well apparently a server restart fixed the issue. Didn't want to restart the server during business hours. Thanks for your help.
