### ISSUE TITLE
[Feature Request] Per-tab "selection color"

### ISSUE THREAD

**Issue by d8ahazard** [mescon/Muximux#92]
Currently, every tab is green when it's active.  I think it would be a neat feature to assign different colors for the various tabs, make an option in settings.  So, I could make CouchPotato Orange, Sonarr Blue, Deluge Green, Plex yellow, etc.  Something like that...

**Comment by mescon** [comment]
Please see my comments on the PR.

**Comment by d8ahazard** [comment]
Done and done!
