### ISSUE TITLE
[feature request] allow setting iframe sandbox options to prevent certain sites from breaking out of iframes

### ISSUE THREAD

**Issue by saveyour** [mescon/Muximux#99]
for example, i have a piwik instance that doesn't appreciate being iframe'd by muximux and "breaks out" by doing a redirect. there is a way to prevent this by using the "sandbox" attribute like so:

>  sandbox="allow-forms allow-popups allow-pointer-lock allow-same-origin allow-scripts"

by adding something like an "advanced edit" check box that allows you to set the sandbox attribute on the iframe this can be prevented.

thanks for creating muximux, keep up the good work!

**Comment by mescon** [comment]
I'd say your use-case isn't generic enough to warrant setting this in the main branch - perhaps you could fork our version and do the changes yourself? Just look in muximux.php and search for "sandbox" and you will find it is currently:
``allow-forms allow-same-origin allow-pointer-lock allow-scripts allow-popups allow-modals allow-top-navigation``

**Comment by saveyour** [comment]
thanks. i just removed allow-top-navigation and it stopped it from breaking out frame
